os: linux
dist: xenial

language: python
python:
  - 3.6
  - 3.7
  - 3.8
cache:
  pip: true

before_install:
  - pip install -r requirements_all.txt
  - pip install -e .
install:
  - python setup.py install
  - python setup.py sdist
